# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11KD_XYs4eplScv75XFrNJZB_7jSLeJVn
"""

import streamlit as st
import pandas as pd
import joblib

# Load the trained model
model = joblib.load('adaboost_model.pkl')

# Title for the Streamlit App
st.title("Bitcoin Price Prediction (High vs. Low)")

# Instructions
st.write("Input the feature values to predict whether the price is High (1) or Low (0).")

# Input fields for features
year = st.number_input("Year", min_value=2000, max_value=2100, value=2023, step=1)
month = st.number_input("Month", min_value=1, max_value=12, value=1, step=1)
day = st.number_input("Day", min_value=1, max_value=31, value=1, step=1)
open_price = st.number_input("Open Price", value=0.0, step=0.01)
high_price = st.number_input("High Price", value=0.0, step=0.01)
low_price = st.number_input("Low Price", value=0.0, step=0.01)
volume = st.number_input("Volume", value=0, step=1)

# Create a DataFrame for the input
input_data = pd.DataFrame({
    'Year': [year],
    'Month': [month],
    'Day': [day],
    'Open': [open_price],
    'High': [high_price],
    'Low': [low_price],
    'Volume': [volume]
})

# Prediction button
if st.button("Predict"):
    # Predict using the loaded model
    prediction = model.predict(input_data)
    result = "High" if prediction[0] == 1 else "Low"
    st.write(f"The predicted price category is: **{result}**")